import { loader } from 'fumadocs-core/source';
// Generated by `fumadocs-mdx` (the `sync-content` Nx target) from
// source.config.ts; this file does not exist until that target has run.
import { docs } from '../../.source/server';

export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
});
