/**
 * Pull request reads addressed by identity: which pull request, read as
 * whom, and which commits its provider reports.
 *
 * Split from `contract.ts` because it is one subject. The types are
 * `@n10/core`'s and `@n10/vcs-core`'s own — the host passes the core
 * snapshot through unchanged — so the renderer and the TUI read the
 * same shape.
 */

export type {
  AspectState,
  CheckList,
  Checkpoint,
  CheckRow,
  CheckStanding,
  DiscardDraftRequest,
  DraftsRequest,
  DraftTarget,
  HistoryRequest,
  MentionSearch,
  MentionSearchRequest,
  Publication,
  PullRequestChecksAnswer,
  PullRequestConversationRead,
  PullRequestHistory,
  PullRequestReadiness,
  PullRequestSnapshot,
  ReadinessAspect,
  ReadinessItem,
  RequirementReason,
  Resolver,
  ReviewDraft,
  ReviewDrafts,
  ReviewerRequirement,
  ReviewerStanding,
  ReviewRequirements,
  RevisionRange,
  RevisionRangeError,
  RevisionRangeErrorCode,
  RevisionRangeResult,
  SaveDraftRequest,
  SnapshotRequest,
  StandingRule,
  SubmitReviewRequest,
  SubmittedReview,
  VisitRequest,
} from '@n10/core';
export type {
  Capability,
  MentionCandidate,
  ConversationActor,
  ConversationComment,
  ConversationEvent,
  ConversationEventKind,
  ConversationThread,
  Coverage,
  LineRange,
  PullRequestConversation,
  ReviewState,
  ReviewSummary,
  ThreadAnchor,
  ThreadStatus,
  Oid,
  PullRequestCheck,
  PullRequestChecks,
  RequiredCheck,
  PullRequestDetail,
  PullRequestLifecycle,
  PullRequestRef,
  PullRequestRevisions,
  ReadOutcome,
  RepositoryRef,
  RevisionEvent,
} from '@n10/vcs-core';
